# Generated by Django 2.2.19 on 2022-02-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-last_name', '-first_name'], 'verbose_name': 'Человек из засписной книжки', 'verbose_name_plural': 'Люди'},
        ),
    ]
