# Generated by Django 2.2.19 on 2022-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonebook_app", "0002_auto_20220219_1731"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_slug", models.SlugField(unique=True)),
                ("amount", models.IntegerField(default=0)),
                ("person_name", models.CharField(max_length=200)),
            ],
        ),
    ]
